services:
  db:
    image: postgres:15
    container_name: notes-postgres
    restart: always
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - notes-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: notes-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/notes?sslmode=disable
    ports:
      - "8080:8080"  # HTTP
      - "9090:9090"  # gRPC
    restart: on-failure

volumes:
  notes-data:
