// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Note struct {
	ID          uuid.UUID    `json:"id"`
	Description string       `json:"description"`
	Created     time.Time    `json:"created"`
	Updated     sql.NullTime `json:"updated"`
}
