// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateNote(ctx context.Context, description string) (Note, error)
	DeleteNoteByID(ctx context.Context, id uuid.UUID) error
	GetAllNotes(ctx context.Context) ([]Note, error)
	GetNoteByID(ctx context.Context, id uuid.UUID) (Note, error)
	UpdateNoteByID(ctx context.Context, arg UpdateNoteByIDParams) (Note, error)
}

var _ Querier = (*Queries)(nil)
